Documentation converted to markdown format.
SCIInstitute/seg3d.pages pull request #2
Opened 2016-09-01 23:56 UTC by collint8

2016-09-14 18:18 UTC, aylakhan commented on Tools/SpeedlineTool.md
> +![alt text]({{ site.github.url }}/images/{{ page.title }}GUI.png)
Missing image? Link looks broken.

2016-09-14 18:24 UTC, aylakhan commented on Tools/IntensityCorrection.md
> +There are two parameters in this filter, * polynomial order* and *edge sensitivity.*
Formatting needs correcting.

2016-09-14 18:33 UTC, aylakhan commented on Tools/ArithmeticFilter.md
> +The arithmetic filter allows the user to run basic arithmetic and boolean operations on both image and mask data on a pixel by pixel basis. This filter can handle up to four inputs and can be used to
Formatting of <expression> needs to be fixed.

2016-09-14 18:35 UTC, a-y-khan requested changes
Please go through the text and format the references to GUI elements consistently. Use a combination of bold & italic. Mouse or key descriptions are fine in bold.

2016-09-23 22:23 UTC, collint8 commented
Formatting is fixed, and italicize/bold has been standardized. The cases you mentioned have also been repaired.

2016-09-26 20:04 UTC, aylakhan commented
This looks really good!

2016-09-26 20:09 UTC, aylakhan commented on Tools/SmoothBinaryErode.md
> +This filter and fast binary dilate -> erode are similar in function, but are slightly different in the results. As the name suggests, smooth binary dilate -> erode will produce a smoother surface aft
Could you please capitalize (and maybe bold or emphasize) filter names in text.

2016-10-04 16:07 UTC, merged